### ISSUE TITLE
undefined: jwt.ExpirationSetting

### ISSUE THREAD

**Issue by luonghaiviet88** [jfcote87/esign#1]
hello jfcote87,
thank for writing a good sdk, but when I try to use, it said that: 
e87/esign/oauth2.go:219:14: undefined: jwt.ExpirationSetting

could you please take a look?

**Comment by jfcote87** [comment]
Sorry about the error.  I updated the repository.  If you are using
modules, set your projects go.mod to use v0.6.0.  Also run a go get -u
regardless.

Thanks for taking a look at it and letting me know.

**Comment by luonghaiviet88** [comment]
wowwww, It works well. Thank you very much!!!
