### ISSUE TITLE
move service packages to v2 directory

### ISSUE THREAD

**Issue by jfcote87** [jfcote87/esign#3]
I'm thinking about making a breaking change by moving the model package and service packages (accounts, authentication, envelopes, etc.) to a v2 directory.  When the v2.1 swagger file is released, I will generate packages in a v2.1 directory allowing developers to use either version or even mix them.

The fix will be simple, just change the import statements to:
```go
import github.com/jfcote87/esign/v2/model
import github.com/jfcote87/esign/v2/{service name}
```

@luonghaiviet88 @reilg

**Comment by reilg** [comment]
@jfcote87 - you are just made of pure awesome man. 
Thank you for the heads up. 

Do you think it would make sense to create the v2 directory now though? 
So we can start using it and not have to worry about the changes happening during our down time or something?

**Comment by steelerc69** [comment]
@jfcote87 
Awesome idea, how soon can you get it done :) along with the 2.1 changes :)

**Comment by jfcote87** [comment]
I should have the 2.0 move done this weekend.  

Version 2.1 will be released as soon as DocuSign to releases their swagger definition file.

**Comment by jfcote87** [comment]
Version 0.7.0 uploaded.  Categories are moved to v2 directory.

**Comment by jfcote87** [comment]
v0.8.0 is released with v2.1 calls and initial implementation of the click API

**Comment by sans-clue** [comment]
@jfcote87 - Hi, I'm having issues updating my existing project to the newest version of this lib using `dep`. Do you have any idea why I'm getting this error? 

```
Solving failure: No versions of github.com/jfcote87/esign met constraints:
        v0.6.3: Could not introduce github.com/jfcote87/esign@v0.6.3, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
        v0.8.0: Could not introduce github.com/jfcote87/esign@v0.8.0, as its subpackage github.com/jfcote87/esign/model is missing. (Package is required by (root).)
        v0.7.0: Could not introduce github.com/jfcote87/esign@v0.7.0, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
        v0.6.2: Could not introduce github.com/jfcote87/esign@v0.6.2, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
        v0.6.0: Could not introduce github.com/jfcote87/esign@v0.6.0, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
        v0.5.0: Could not introduce github.com/jfcote87/esign@v0.5.0, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
        master: Could not introduce github.com/jfcote87/esign@master, as it is not allowed by constraint ^0.8.0 from project gitlab.com/my/project.
```

Not really sure what to do at this point.

**Comment by jfcote87** [comment]
I have not used dep.  It looks like one of your file import github.com/jfcote87/esign/model.  It should be github.com/jfcote87/esign/v2/model or github.com/jfcote87/esign/v2.1/model
