### ISSUE TITLE
Error Unmarshal JSON

### ISSUE THREAD

**Issue by simplysivu** [jfcote87/esign#5]
Hi @jfcote87 ,

Thanks for this awesome library. It made my job much easier.
When trying to update an existing envelope(in the created state) which is equivalent to 
`PUT https://demo.docusign.net/restapi/v2/accounts/10150368/envelopes/e24941f6-8c68-4e78-ab54-f79e206f57ae/recipients/1/tabs 
Request Body:
{
  "textTabs": [
    {
      "documentId": "1",
      "pageNumber": "1",
      "tabLabel": "Name",
      "value": "Jon snow",
      "xPosition": "195",
      "yPosition": "1600"
    }
  ]
}
`
I see an error at (https://github.com/jfcote87/esign/blob/471db206b28a61d544cb31a316fbaee29ea2f393/esign.go#L262) 
The error is `error updaing document: json: cannot unmarshal string into Go struct field Text.tabUpdateResults.textTabs.width of type int32`
After debugging I found that the response body which we are trying to marshal into model.EnvelopeUpdateSummary contains width and height of type string.

It means the response body contains width and height has string type but the model.Text.Widht and model.Text.Height are of type int32.

**Comment by simplysivu** [comment]
The other numeric fields like model.Text.PageNumber and model.Text.TextPosition.XPosition and model.Text.TextPosition.YPosition are specified as strings. 
Is there any reason why width and height are specified as int

**Comment by simplysivu** [comment]
Could you please provide me access, so I can send a pull request.

**Comment by jfcote87** [comment]
I've opened pull requests, so you should be able to send one now.

> Is there any reason why width and height are specified as int

The v2 swagger definition lists height and weight fields as int32's.  In v2.1 they changed them to strings.  It appears that they have now applied the changes to v2 without providing a new specification.  The gen-esign command creates all files in the v2 and v2.1 directories, so it should be best to modify the code there.  Also, if anyone needs this fixed immediately, use v2.1 definitions instead of v2.

**Comment by simplysivu** [comment]
Hi @jfcote87,

My changes are in gen-esign. I have updated override.go
Still, I don't have access to push my local changes to a remote branch.
Could you please provide me access so that I can create a PR.

Thanks and Regards,
Siva.

**Comment by simplysivu** [comment]
Please review it https://github.com/jfcote87/esign/pull/6

**Comment by simplysivu** [comment]
Hi @jfcote87, Thanks for merging it. Could you please create the release for the changes. 
https://github.com/jfcote87/esign/releases

**Comment by ContraBoy9999** [comment]
@simplysivu - did you try implementing the embedded signing ceremony with this Sdk?  Request a Recipient View URL (the Signing Ceremony URL). Is this functionality supported?
